#!/bin/bash
# Created by https://www.hostingtermurah.net
# Modified by Jeypi04
#Requirement
if [ ! -e /usr/bin/curl ]; then
   yum -y install curl
fi

# initializing var
OS=`uname -m`;
MYIP=$(curl -4 icanhazip.com)
if [ $MYIP = "" ]; then
   MYIP=`ifconfig | grep 'inet addr:' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d: -f2 | awk '{ print $1}' | head -1`;
fi
MYIP2="s/xxxxxxxxx/$MYIP/g";

# go to root
cd

# setting repo
wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
wget http://rpms.remirepo.net/enterprise/remi-release-7.rpm
rpm -Uvh epel-release-latest-7.noarch.rpm
rpm -Uvh remi-release-7.rpm
wget http://repository.it4i.cz/mirrors/repoforge/redhat/el7/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm
rpm -Uvh rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm
sed -i 's/enabled = 1/enabled = 0/g' /etc/yum.repos.d/rpmforge.repo
sed -i -e "/^\[remi\]/,/^\[.*\]/ s|^\(enabled[ \t]*=[ \t]*0\\)|enabled=1|" /etc/yum.repos.d/remi.repo
rm -f *.rpm

# set time GMT +8
ln -fs /usr/share/zoneinfo/Asia/Manila /etc/localtime

# disable se linux
echo 0 > /selinux/enforce
sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

# set locale
sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
service sshd restart

# disable ipv6
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.d/rc.local

#Add DNS Server ipv4
echo "nameserver 1.1.1.1" > /etc/resolv.conf
echo "nameserver 1.0.0.1" >> /etc/resolv.conf
sed -i '$ i\echo "nameserver 1.1.1.1" > /etc/resolv.conf' /etc/rc.local
sed -i '$ i\echo "nameserver 1.0.0.1" >> /etc/resolv.conf' /etc/rc.local
sed -i '$ i\echo "nameserver 1.1.1.1" > /etc/resolv.conf' /etc/rc.d/rc.local
sed -i '$ i\echo "nameserver 1.0.0.1" >> /etc/resolv.conf' /etc/rc.d/rc.local

# install wget and curl
yum -y install nano wget curl
yum -y install firewalld
systemctl start firewalld
systemctl enable firewalld

# install ddos deflate
cd
wget http://www6.atomicorp.com/channels/atomic/centos/7/x86_64/RPMS/grepcidr-2.0-1.el7.art.x86_64.rpm
rpm -Uvh grepcidr-2.0-1.el7.art.x86_64.rpm
yum install grepcidr
yum -y install dnsutils bind-utils dsniff unzip net-snmp net-snmp-utils tcpdump
wget https://github.com/jgmdev/ddos-deflate/archive/master.zip
unzip master.zip
cd ddos-deflate-master
./install.sh
rm -rf /root/master.zip
cd

# setting banner
rm /etc/issue.net -f
wget -O /etc/issue.net "https://raw.githubusercontent.com/Jeypi04/openvpn-centos7/master/issue.net"
sed -i '/Banner/a Banner="/etc/issue.net"' /etc/ssh/sshd_config
sed -i 's@DROPBEAR_BANNER=""@DROPBEAR_BANNER="/etc/issue.net"@g' /etc/default/dropbear


# install openvpn
yum -y install openvpn
wget -O /tmp/easyrsa https://github.com/OpenVPN/easy-rsa-old/archive/2.3.3.tar.gz
tar xfz /tmp/easyrsa
mkdir /etc/openvpn/easy-rsa
cp -rf easy-rsa-old-2.3.3/easy-rsa/2.0/* /etc/openvpn/easy-rsa
mkdir /etc/openvpn/easy-rsa/keys
sed -i 's/export PKCS11/#export PKCS11/g' /etc/openvpn/easy-rsa/vars
sed -i 's/export KEY_CN/#export KEY_CN/g' /etc/openvpn/easy-rsa/vars
sed -i 's/export KEY_EMAIL=mail@host.domain/#export KEY_EMAIL=mail@host.domain/g' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_COUNTRY="PH"|export KEY_COUNTRY="PH"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_PROVINCE="NE"|export KEY_PROVINCE="Manila"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_CITY="Cabanatuan"|export KEY_CITY="Sampaloc"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_ORG="Fort-Funston"|export KEY_ORG="jeypi"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_EMAIL="me@myhost.mydomain"|export KEY_EMAIL="jeypi@gmail.com"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_NAME=changeme|export KEY_NAME="server"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_OU=changeme|export KEY_OU="JPvpn"|' /etc/openvpn/easy-rsa/vars
#Create Diffie-Helman Pem
openssl dhparam -out /etc/openvpn/dh2048.pem 2048
# Create PKI
cd /etc/openvpn/easy-rsa
cp openssl-1.0.0.cnf openssl.cnf
. ./vars
./clean-all
export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" --initca $*
# create key server
export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" --server server
# setting KEY CN
export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" client
cd
cd /etc/openvpn/easy-rsa/keys
cp ca.crt server.crt server.key /etc/openvpn
cd
# setting server
cat > /etc/openvpn/server.conf <<-END
port 465
proto tcp
dev tun
ca ca.crt
cert server.crt
key server.key 
dh dh2048.pem
client-cert-not-required
username-as-common-name
plugin /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so login
server 192.168.100.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"
push "route-method exe"
push "route-delay 2"
duplicate-cn
push "route-method exe"
push "route-delay 2"
keepalive 10 120
persist-key
persist-tun
status openvpn-status.log
log openvpn.log
comp-lzo no
push "comp-lzo no"
cipher none
auth none
verb 3
END

cd

# create openvpn config
cat > openvpn.ovpn <<-END
#modified by Jeypi04
client
dev tun
proto tcp
remote xxxxxxxxx 465
persist-key
persist-tun
dev tun
pull
resolv-retry infinite
nobind
ns-cert-type server
verb 3
mute 2
mute-replay-warnings
auth-user-pass
setenv opt block-outside-dns
redirect-gateway def1
script-security 2
route 0.0.0.0 0.0.0.0
route-method exe
route-delay 2
cipher none
setenv CLIENT_CERT 0
dhcp-option DOMAIN 1dot1dot1dot1.cloudflare-dns.com

END
echo '<ca>' >> openvpn.ovpn
cat /etc/openvpn/ca.crt >> openvpn.ovpn
echo '</ca>' >> openvpn.ovpn
sed -i $MYIP2 openvpn.ovpn;

#setup firewall
firewall-cmd --get-active-zones
firewall-cmd --zone=trusted --add-service openvpn
firewall-cmd --zone=trusted --add-service openvpn --permanent
firewall-cmd --list-services --zone=trusted
firewall-cmd --add-masquerade
firewall-cmd --permanent --add-masquerade
firewall-cmd --query-masquerade
SHARK=$(ip route get 1.1.1.1 | awk 'NR==1 {print $(NF-2)}')
firewall-cmd --permanent --direct --passthrough ipv4 -t nat -A POSTROUTING -s 192.168.100.0/24 -o $SHARK -j MASQUERADE
firewall-cmd --zone=public --add-port=1194/tcp --permanent
firewall-cmd --reload
#forward ipv4
sysctl -w net.ipv4.ip_forward=1
touch /usr/lib/sysctl.d/sysctl.conf
cat > /usr/lib/sysctl.d/sysctl.conf <<-END
net.ipv4.ip_forward = 1
END
systemctl restart network.service
systemctl -f enable openvpn@server.service
systemctl start openvpn@server.service
systemctl status openvpn@server.service
chkconfig openvpn on


# install squid



# download script
cd
wget https://raw.githubusercontent.com/shigeno143/OCSPanelCentos6/master/install-premiumscript.sh -O - -o /dev/null|sh
touch /root/log.txt
cat > /root/log.txt <<-END
"---------------------------Squid Commands---------------------------"
"           to start:    # /usr/sbin/squid                           "
"            to stop:    # /usr/sbin/squid -k shutdown               "
"          to reload:    # /usr/sbin/squid -k reconfigure            "
" to test if running:    # ps uax|grep squid                         "
"      to check logs:    # tail /var/logs/cache.log                  "
"--------------------------------------------------------------------"
"-------------------------OpenVPN Commands---------------------------"
"           to start:    # systemctl start openvpn@server.service    "
"            to stop:    # systemctl stop openvpn@server.service     "
"          to reload:    # systemctl restart openvpn@server.service  "
"    to check status:    # systemctl status openvpn@server.service   "
"--------------------------------------------------------------------"
"----------------------     Add Users     ---------------------------"
"             to add:    # useradd enterusernamehere                 "
"      change passwd:    # echo "username:password" | chpasswd       "
"          to remove:    # userdel username                          "
"--------------------------------------------------------------------"
Application & Port Information
   - OpenVPN     : TCP 1194 
   - Squid Proxy : 80, 8000, 8080, 8888, 3128 (limit to IP Server)
END

#clearing history
history -c

# info
clear

echo " "
echo "INSTALLATION COMPLETE!"
echo " "
echo "---------------------------Squid Commands---------------------------"
echo "           to start:    # /usr/sbin/squid                           "
echo "            to stop:    # /usr/sbin/squid -k shutdown               "
echo "          to reload:    # /usr/sbin/squid -k reconfigure            "
echo " to test if running:    # ps uax|grep squid                         "
echo "      to check logs:    # tail /var/logs/cache.log                  "
echo "--------------------------------------------------------------------"
echo "-------------------------OpenVPN Commands---------------------------"
echo "           to start:    # systemctl start openvpn@server.service    "
echo "            to stop:    # systemctl stop openvpn@server.service     "
echo "          to reload:    # systemctl restart openvpn@server.service  "
echo "    to check status:    # systemctl status openvpn@server.service   "
echo "--------------------------------------------------------------------"
echo "----------------------     Add Users     ---------------------------"
echo "             to add:    # useradd enterusernamehere                 "
echo "      change passwd:    # echo "username:password" | chpasswd       "
echo "          to remove:    # userdel username                          "
echo "--------------------------------------------------------------------"
echo "Application & Port Information"
echo "   - OpenVPN     : TCP 1194 "
echo "   - Squid Proxy : 80, 8000, 8080, 8888, 3128 (limit to IP Server)" 
echo " "
echo "----- Script Created By Steven Indarto(fb.com/stevenindarto2) ------"
echo " Modified By Jeypi04 (https://www.phcorner.net/members/429068/)"
