#!/bin/bash
apt update && apt upgrade -y
if [ "$(id -u)" -ne 0 ]; then
	echo -ne "\nPlease execute this script as root.\n"
	exit 1; fi
if [ ! -f /etc/debian* ]; then
	echo -ne "\nFor Debian distro only.\n"
	exit 1; fi
export DEBIAN_FRONTEND=noninteractive

apt install -y openvpn
dirx=/etc/openvpn
mkdir $dirx/log
wget https://github.com/X-DCB/RADZ-VPN/raw/master/openvpn.tar.gz -qO- | tar xz -C $dirx
IP=`wget -qO- ipv4.icanhazip.com`
cat > /root/client.ovpn << config
client
tls-client
dev tun
proto tcp
remote $IP 465
route-method exe
mute-replay-warnings
verb 3
auth-user-pass
cipher none
auth none
remote-cert-tls server
key-direction 1
http-proxy $IP 8080

<ca>
`cat $dirx/keys/ca.crt`
</ca>
<cert>
`cat $dirx/keys/client.crt`
</cert>
<key>
`cat $dirx/keys/client.key`
</key>
config

systemctl restart openvpn

wget https://raw.githubusercontent.com/ndndndn/CodesX/main/sq3.sh && bash sq3.sh
wget https://raw.githubusercontent.com/padubang/gans/main/setupmenu && bash setupmenu

echo -e "\nOpenVPN installed."
echo "Script by Dexter Cellona Banawon"
exit 0
